/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/criar-conta' | '/entrar' | '/recuperar-password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/criar-conta' | '/entrar' | '/recuperar-password'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
